[project]
name = "miz-mhc"
version = "0.0.1a0"
description = "RDB with MetaHub and TemplateClient"
readme = "ReadMe.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "mh-backend",
    "tc-backend",
]
